name: CI/CD - ERDiagramGenerator

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH into EC2 and Deploy with Docker
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.INSTANCE_IP }} << EOF
          set -e

          echo "[+] Cloning or pulling latest code..."
          if [ ! -d "ERDiagramGenerator" ]; then
            git clone https://github.com/Aswin-AR5055/ERDiagramGenerator.git ERDiagramGenerator
          fi

          cd ERDiagramGenerator

          git pull

          echo "[+] Stopping and removing existing container..."
          sudo docker stop erdiagram || true
          sudo docker rm erdiagram || true

          echo "[+] Removing existing Docker image..."
          sudo docker rmi -f ergenerator || true

          echo "[+] Building new Docker image..."
          sudo docker build -t ergenerator .

          echo "[+] Running new container on port 8000..."
          sudo docker run -d --name erdiagram \
            -p 8000:8000 \
            ergenerator

          echo "[+] Done! Current containers:"
          sudo docker ps
        EOF
